#!/bin/sh

set -e

TABLE=""

die() {
	echo "error: $@" 1>&2
	exit 1
}

NUMBERS=`mktemp /tmp/check-num.XXXXXXXXXXXXXXX` || exit 1
trap 'rm $TABLE $NUMBERS' exit
TABLE=`mktemp /tmp/check-tab.XXXXXXXXXXXXXXX` || exit 1


awk '/^[0-9.]* *Message type numbers/{flag=1} /^[0-9.]* *Reserved message type numbers/{flag=0} flag' draft-ietf-sshm-ssh-agent.txt | grep "^ *SSH_AGENT.* *[0-9]" > $NUMBERS

awk '/^[0-9.]* *New registry: SSH agent protocol message type numbers/{flag=1} /^ *Table [0-9]* *$/{flag=0} flag' draft-ietf-sshm-ssh-agent.txt | grep "SSH_AGENT" > $TABLE

# Check all numbers in "Message type numbers" are also listed in IANA section.
for name in `awk '{print $1}' < $NUMBERS` ; do
	number=`grep "^ *$name *" $NUMBERS | awk '{print $2}'`

	grep -q " $number *.* *$name" $TABLE || \
		die "$name $number missing from IANA section"
done

# Check all numbers in IANA section are listed in "Message type numbers"
for name in `cut -d'|' -f3 < $TABLE` ; do
	number=`grep " $name " $TABLE | cut -d'|' -f2 | tr -d ' '`
	grep -q "^ *$name * $number *" $NUMBERS || \
		die "$name $number missing from Message type numbers"
done
